//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class registerallocation<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   Integer line_counter= 1;
   Integer arg= 0;
   blockinfo current_block= new blockinfo(1);
   functioninfo current_function= new functioninfo("main");
   public Map<String, functioninfo> function_map= new HashMap<String, functioninfo>();
   ArrayList <String> registers= new ArrayList<String>(Arrays.asList("s0","s1","s2","s3","s4","s5","s6","s7","t0","t1","t2","t3","t4","t5","t6","t7","t8","t9"));
   Integer free_reg= 18;
   Map<String, Integer> label_linemap= new HashMap<String, Integer>();
   boolean label_status= false;
   Integer argcounter= 0;
   Integer stack_ptr= 0;
   Boolean v0_status= false;
   Boolean v1_status= false;
   Boolean arg_check= false;
   void fun(String temp, String reg) {
      String alloc_reg= "-1";
      if(current_function.interval_map.containsKey(temp)) {
         intervalinfo interval= current_function.interval_map.get(temp);
         if(!interval.allocated_register.equals("-1")) {
            alloc_reg= current_function.interval_map.get(temp).allocated_register;
            System.out.println("\tMOVE " + alloc_reg + " " + reg);
         }
         else{
            alloc_reg= "v0";
            System.out.println("MOVE " + alloc_reg + " " + reg);
            Integer i= Math.max(0,current_function.num_args -4)+ current_function.stack_ptr;
            System.out.println("\tASTORE SPILLEDARG " + i + " " + alloc_reg);
         }
      }
   }
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String function_name= "MAIN";
      current_function= function_map.get(function_name);
      stack_ptr= current_function.stack_ptr;
      System.out.println(function_name+ "[ "+ current_function.num_args+" ] [ "+ current_function.total_stack_size+" ] ["+ current_function.max_callee_args+" ]");
      line_counter++;
      n.f1.accept(this, argu);
      System.out.println("END");
      line_counter++;
      
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      label_status= true;
      n.f0.accept(this, argu);
      label_status= false;
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String function_name= n.f0.f0.toString();
      current_function= function_map.get(function_name);
      stack_ptr= current_function.stack_ptr;
      System.out.println(function_name+ "[ "+ current_function.num_args+" ] [ "+ current_function.total_stack_size+" ] ["+ current_function.max_callee_args+" ]");
      line_counter++;

      for(int i=0; i<8; i++) {
         System.out.println("\tASTORE SPILLEDARG " + stack_ptr +" s" + i);
         stack_ptr ++;
      }

      for(int i=0; i< current_function.num_args; i++) {
         if(i<4) {
            fun("TEMP " + i, "a"+ i);
         }
      }

      for(int i=4; i< current_function.num_args; i++) {
         System.out.println("\tALOAD v0 SPILLEDARG " + (i-4));
         fun("TEMP " + i, "v0");
      }
      n.f4.accept(this, argu);

      for(int i=7; i>=0; i--){
         stack_ptr --;
         System.out.println("\tALOAD s" + i + " SPILLEDARG " + stack_ptr);
      }
      System.out.println("END");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("\tNOOP");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("\tERROR");
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      v0_status= true;
      String alloc_reg= (String)n.f1.accept(this, argu);
      v0_status= false;
      label_status= true;
      String label= (String)n.f2.accept(this, argu);
      label_status= false;
      System.out.println("\tCJUMP " + alloc_reg + " " + label);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      label_status= true;
      String label= (String)n.f1.accept(this, argu);
      label_status= false;
      System.out.println("\tJUMP " + label);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      v0_status= true;
      String alloc_reg1= (String)n.f1.accept(this, argu);
      v0_status= false;
      v1_status= true;
      String offset= (String)n.f2.accept(this, argu);
      v1_status= false;
      String alloc_reg2= (String)n.f3.accept(this, argu);
      System.out.println("\tHSTORE " + alloc_reg1 + " " + offset + " " + alloc_reg2);
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String var= "TEMP "+ (String)n.f1.f1.f0.toString();
      v0_status= true;
      String alloc_reg= (String)n.f2.accept(this, argu);
      v0_status= false;
      String offset= (String)n.f3.accept(this, argu);
      System.out.println("\tHLOAD v0 "+ alloc_reg+ " " + offset);
      fun(var, "v0");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String var= "TEMP "+ (String)n.f1.f1.f0.toString();
      label_status= true;
      String exp= (String)n.f2.accept(this, argu);
      label_status= false;
      fun(var, exp);
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String alloc_reg= (String)n.f1.accept(this, argu);
      System.out.println("\tPRINT " + alloc_reg);
      return _ret;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      String exp= (String)n.f0.accept(this, argu);
      return (R)exp;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String reg= (String)n.f3.accept(this, argu);
      System.out.println("\tMOVE v0 " + reg);
      n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String func_reg= (String)n.f1.accept(this, argu);
      for(int i=0; i<10; i++){
			System.out.println("\tASTORE SPILLEDARG " + stack_ptr + " t" + i);
         stack_ptr ++;
      }
      n.f2.accept(this, argu);
      arg_check= true;
      argcounter= 0;
      n.f3.accept(this, argu);
      arg_check= false;
      n.f4.accept(this, argu);
      System.out.println("\tCALL " + func_reg);
      for(int i=9; i>=0; i--){
         stack_ptr --;
         System.out.println("\tALOAD t" + i + " SPILLEDARG " + stack_ptr);
      }
      return (R)"v0";
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String alloc_reg= (String)n.f1.accept(this, argu);

      return (R)("\tHALLOCATE " + alloc_reg);
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      String op= (String)n.f0.accept(this, argu);
      v1_status= true;
      String left= (String)n.f1.accept(this, argu);
      v1_status= false;
      String right= (String)n.f2.accept(this, argu);
      String ret= op+ " " + left + " " + right;
      return (R)ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      String op= n.f0.choice.toString();
      return (R)op;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      v0_status= true;
      String temp= (String)n.f0.accept(this, argu);
      v0_status= false;
      return (R)temp;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String temp_name= "TEMP "+ n.f1.f0.toString();
      String alloc_reg= "v0";
      if(v1_status){
         alloc_reg= "v1";
      }
      if(current_function.interval_map.containsKey(temp_name)) {
         intervalinfo interval= current_function.interval_map.get(temp_name);
         if(!interval.allocated_register.equals("-1")) {
            alloc_reg= current_function.interval_map.get(temp_name).allocated_register;
         }
         else{
            Integer i= Math.max(0,current_function.num_args -4)+ current_function.stack_ptr;
            System.out.println("\tALOAD " + alloc_reg + " SPILLEDARG " + i);
            alloc_reg= "v1";
         }
      }

      if(arg_check){
         if(argcounter <4){
            System.out.println("\tMOVE a"+ (argcounter) + " " + alloc_reg);
         }
         else{
            System.out.println("\tPASSARG " + (argcounter -4) + " " + alloc_reg);
         }
      }
      return (R)alloc_reg;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String value= n.f0.toString();
      return (R)value;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      String label= n.f0.toString();
      if(!label_status){
         System.out.println(current_function.function_name + "_" + label);
      }
      return (R)label;
   }

}
