//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   Integer cur_maxarg= 0;
   Integer cur_arg= 0;
   Integer cur_childargs= 0;

   boolean fun1(String off){
      Integer offset= Integer.parseInt(off);
      return offset<(4*cur_maxarg);
   }

   Integer fun2(Integer off){
      String offset= Integer.toString(off);
      if(cur_childargs==0 && cur_arg>0 && !fun1(offset)){
         off-= cur_arg*4;
         return off;
      }
      else if(cur_childargs>0 && cur_arg==0){
         off+= cur_childargs*4;
         return off;
      }
      else return off;
   }
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      Integer args= Math.max(0,Integer.parseInt(n.f2.f0.toString())-4);
      String stacksize= Integer.toString(4*Integer.parseInt(n.f5.f0.toString())+4);
      Integer max_childargs= Math.max(0,Integer.parseInt(n.f8.f0.toString())-4);
      cur_maxarg= Math.max(Math.max(max_childargs-4,args-4),0);
      cur_arg= args;
      cur_childargs= max_childargs;
      String total_stacksize= Integer.toString(Integer.parseInt(stacksize)+4*max_childargs-4*args);
      System.out.println("\t.text\n\t.globl\tmain\nmain:");
      System.out.println("\tmove $fp, $sp");
      System.out.println("\tsw $ra, -4($fp)");
      System.out.println("\tsubu $sp, $sp, " + (total_stacksize));

      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      System.out.println("\taddu $sp, $sp, " + (total_stacksize));
      System.out.println("\tlw $ra, -4($fp)");
      System.out.println("\tj $ra");
      n.f13.accept(this, argu);
      n.f14.accept(this, argu);

      System.out.println("\t.text\n\t.globl _halloc\n_halloc:\n\tli $v0, 9\n\tsyscall\n\tj $ra\n");
      System.out.println("\t.text\n\t.globl _print\n_print:\n\tli $v0, 1\n\tsyscall\n\tla $a0, newl\n\tli $v0, 4\n\tsyscall\n\tj $ra\n");
      System.out.println("\t.data\n\t.align 0\nnewl:\t.asciiz \"\\n\"\n\t.data\n\t.align 0\nstr_er:\t.asciiz \"ERROR: abnormal termination\\n\"");

      return _ret;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      R _ret=null;
      //print label
      if (n.f0.present()) {
         for (Enumeration<Node> e = n.f0.elements(); e.hasMoreElements(); ) {
            NodeSequence seq = (NodeSequence) e.nextElement();
            if (seq.nodes.size() == 2) { // (Label)? + Stmt
               Node first = seq.nodes.get(0);
               if (first instanceof Label) {
                  Label lbl = (Label) first;
                  System.out.println(lbl.f0.toString() + ":");
               }
               else if (first instanceof NodeOptional) {
                  NodeOptional opt = (NodeOptional) first;
                  if (opt.present() && opt.node instanceof Label) {
                     Label lbl = (Label) opt.node;
                     if (lbl != null && lbl.f0 != null)
                        System.out.println(lbl.f0.toString() + ":");
                  }
               }
               seq.nodes.get(1).accept(this, argu); // Stmt
            } else { 
               seq.nodes.get(0).accept(this, argu); // Stmt
            }
         }
      }
      return _ret;
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String func_name= n.f0.f0.toString();
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      Integer args= Math.max(0,Integer.parseInt(n.f2.f0.toString())-4);
      String stacksize= Integer.toString(4*Integer.parseInt(n.f5.f0.toString())+8);
      Integer max_childargs= Math.max(0,Integer.parseInt(n.f8.f0.toString())-4);
      cur_maxarg= Math.max(Math.max(max_childargs,args),0);
      cur_arg= args;
      cur_childargs= max_childargs;
      String total_stacksize= Integer.toString(Integer.parseInt(stacksize)+4*max_childargs-4*args);
      //System.err.println(cur_arg+" "+cur_childargs+" "+cur_maxarg);
      System.out.println("\t.text\n\t.globl\t" + func_name + "\n" + func_name + ":\n");
      System.out.println("\tsw $fp, -8($sp)");
      System.out.println("\tmove $fp, $sp");
      System.out.println("\tsw $ra, -4($fp)");
      System.out.println("\tsubu $sp, $sp, " + (total_stacksize));
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f11.accept(this, argu);
      n.f12.accept(this, argu);
      System.out.println("\taddu $sp, $sp, " + (total_stacksize));
      System.out.println("\tlw $ra, -4($fp)");;
      System.out.println("\tlw $fp, -8($sp)");
      System.out.println("\tj $ra");
      System.out.println("");
      return _ret;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      System.out.println("\tnop");
      return _ret;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      System.out.println("\tli $v0, 4\n\tla $a0, str_er\n\tsyscall\n\tli $v0, 10\n\tsyscall");
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg= n.f1.f0.choice.toString();
      String label= n.f2.f0.toString();
      System.out.println("\tbeqz $" + reg  + " " + label);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String label= n.f1.f0.toString();
      System.out.println("\tb " + label);
      return _ret;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg1= n.f1.f0.choice.toString();
      String offset= Integer.toString(Integer.parseInt(n.f2.f0.toString()));
      String reg2= n.f3.f0.choice.toString();
      System.out.println("\tsw $" + reg2 + ", " + offset + "($" + reg1 + ")");
      return _ret;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg1= n.f1.f0.choice.toString();
      String reg2= n.f2.f0.choice.toString();
      String offset= Integer.toString(Integer.parseInt(n.f3.f0.toString()));
      System.out.println("\tlw $" + reg1 + ", " + offset + "($" + reg2 + ")");
      return _ret;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String reg= n.f1.f0.choice.toString();
      n.f2.accept(this, argu);
      if(n.f2.f0.choice instanceof SimpleExp) {
         SimpleExp se= (SimpleExp) n.f2.f0.choice;
         if(se.f0.choice instanceof IntegerLiteral) {
            IntegerLiteral il= (IntegerLiteral) se.f0.choice;
            String value= il.f0.toString();
            System.out.println("\tli $" + reg + " " + value);
         }
         else if(se.f0.choice instanceof Label) {
            Label l= (Label) se.f0.choice;
            String label= l.f0.toString();
            System.out.println("\tla $" + reg + " " + label);
         }
         else if(se.f0.choice instanceof Reg) {
            Reg r= (Reg) se.f0.choice;
            String srcreg= r.f0.choice.toString();
            System.out.println("\tmove $" + reg + " $" + srcreg);
         }
      }
      else if(n.f2.f0.choice instanceof BinOp) {
         BinOp bo= (BinOp) n.f2.f0.choice;
         String srcreg= bo.f1.f0.choice.toString();
         Operator op = bo.f0;
         String operator = op.f0.choice.toString();
         if(operator.equals("PLUS")) {
            if(bo.f2.f0.choice instanceof IntegerLiteral) {
               IntegerLiteral il= (IntegerLiteral) bo.f2.f0.choice;
               String value= il.f0.toString();
               System.out.println("\taddi $" + reg + ", $" + srcreg + ", " + value);
            }
            else if(bo.f2.f0.choice instanceof Reg) {
               Reg r= (Reg) bo.f2.f0.choice;
               String reg2= r.f0.choice.toString();
               System.out.println("\tadd $" + reg + ", $" + srcreg + ", $" + reg2);
            }
         }
         else if(operator.equals("MINUS")) {
            if(bo.f2.f0.choice instanceof IntegerLiteral) {
               IntegerLiteral il= (IntegerLiteral) bo.f2.f0.choice;
               String value= il.f0.toString();
               System.out.println("\tsub $" + reg + ", $" + srcreg + ",  " + value);
            }
            else if(bo.f2.f0.choice instanceof Reg) {
               Reg r= (Reg) bo.f2.f0.choice;
               String reg2= r.f0.choice.toString();
               System.out.println("\tsub $" + reg + ", $" + srcreg + ", $" + reg2);
            }
         }
         else if(operator.equals("TIMES")) {
            if(bo.f2.f0.choice instanceof IntegerLiteral) {
               IntegerLiteral il= (IntegerLiteral) bo.f2.f0.choice;
               String value= il.f0.toString();
               System.out.println("\tmul $" + reg + ", $" + srcreg + ", " + value);
            }
            else if(bo.f2.f0.choice instanceof Reg) {
               Reg r= (Reg) bo.f2.f0.choice;
               String reg2= r.f0.choice.toString();
               System.out.println("\tmul $" + reg + ", $" + srcreg + ", $" +  reg2);
            }
         }
         else if(operator.equals("DIV")) {
            if(bo.f2.f0.choice instanceof IntegerLiteral) {
               IntegerLiteral il= (IntegerLiteral) bo.f2.f0.choice;
               String value= il.f0.toString();
               System.out.println("\tdiv $" + reg + ", $" + srcreg + ", " + value);
            }
            else if(bo.f2.f0.choice instanceof Reg) {
               Reg r= (Reg) bo.f2.f0.choice;
               String reg2= r.f0.choice.toString();
               System.out.println("\tdiv $" + reg + ", $" + srcreg + ", $" +  reg2);
            }
         }
         else if(operator.equals("LE")) {
            if(bo.f2.f0.choice instanceof IntegerLiteral) {
               IntegerLiteral il= (IntegerLiteral) bo.f2.f0.choice;
               String value= il.f0.toString();
               System.out.println("\tsle $" + reg + ", $" + srcreg + ", " + value);
            }
            else if(bo.f2.f0.choice instanceof Reg) {
               Reg r= (Reg) bo.f2.f0.choice;
               String reg2= r.f0.choice.toString();
               System.out.println("\tsle $" + reg + ", $" + srcreg + ", $" + reg2);
            }
         }
         else if(operator.equals("NE")) {
            if(bo.f2.f0.choice instanceof IntegerLiteral) {
               IntegerLiteral il= (IntegerLiteral) bo.f2.f0.choice;
               String value= il.f0.toString();
               System.out.println("\tsne $" + reg + ", $" + srcreg + ", " + value);
            }
            else if(bo.f2.f0.choice instanceof Reg) {
               Reg r= (Reg) bo.f2.f0.choice;
               String reg2= r.f0.choice.toString();
               System.out.println("\tsne $" + reg + ", $" + srcreg + ", $" + reg2);
            }
         }
      }
      else{
         //HAllocate
         HAllocate ha= (HAllocate) n.f2.f0.choice;
         if(ha.f1.f0.choice instanceof Reg) {
            Reg r= (Reg) ha.f1.f0.choice;
            String sizereg= r.f0.choice.toString();
            System.out.println("\tmove $a0 $" + sizereg);
         }
         else if(ha.f1.f0.choice instanceof IntegerLiteral) {
            IntegerLiteral il= (IntegerLiteral) ha.f1.f0.choice;
            String size= il.f0.toString();
            System.out.println("\tli $a0 " + size);
         }
         
         System.out.println("\tjal _halloc");
         System.out.println("\tmove $" + reg + " $v0");
      }
      return _ret;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      if(n.f1.f0.choice instanceof Reg) {
         Reg r= (Reg) n.f1.f0.choice;
         String reg= r.f0.choice.toString();
         System.out.println("\tmove $a0 $" + reg);
         System.out.println("\tjal _print");
      }
      else if(n.f1.f0.choice instanceof IntegerLiteral) {
         IntegerLiteral il= (IntegerLiteral) n.f1.f0.choice;
         String value= il.f0.toString();
         System.out.println("\tli $a0 " + value);
         System.out.println("\tjal _print");
      }
      return _ret;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public R visit(ALoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String reg= n.f1.f0.choice.toString();
      Integer off= Integer.parseInt(n.f2.f1.f0.toString());
      Integer adjusted_off= fun2(off*4);
      String finaloff= Integer.toString(adjusted_off);
      if(cur_arg>0 && cur_childargs>0 && fun1(finaloff)) {
         System.out.println("\tlw $" + reg + ", " + finaloff + "($fp)");
      }
      else if(cur_arg>0 && cur_childargs==0 && fun1(Integer.toString(off*4))){
         System.out.println("\tlw $" + reg + ", " + finaloff + "($fp)");
      }
      else System.out.println("\tlw $" + reg + ", " + finaloff + "($sp)");
      //System.err.println(reg+" "+off+" "+finaloff+" "+cur_childargs+" "+cur_arg);
      return _ret;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public R visit(AStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String reg= n.f2.f0.choice.toString();
      Integer off= Integer.parseInt(n.f1.f1.f0.toString());
      Integer adjusted_off= fun2(off*4);
      String finaloff= Integer.toString(adjusted_off);
      if(cur_arg>0 && cur_childargs>0 && fun1(finaloff)) {
         System.out.println("\tsw $" + reg + ", " + finaloff + "($fp)");
      }
      else if(cur_arg>0 && cur_childargs==0 && fun1(Integer.toString(off*4))){
         System.out.println("\tsw $" + reg + ", " + finaloff + "($fp)");
      }
      else System.out.println("\tsw $" + reg + ", " + finaloff + "($sp)");
      
      return _ret;
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public R visit(PassArgStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
   n.f1.accept(this, argu);
   n.f2.accept(this, argu);
   String offset = Integer.toString(4 * (Integer.parseInt(n.f1.f0.toString()) - 1));
   String reg = n.f2.f0.choice.toString();
      System.out.println("\tsw $" + reg + ", " + offset + "($sp)");
      return _ret;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public R visit(CallStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      if (n.f1.f0.choice instanceof Reg) {
         Reg r = (Reg) n.f1.f0.choice;
         String reg = r.f0.choice.toString();
         System.out.println("\tjalr $" + reg);
      }
      else if (n.f1.f0.choice instanceof Label) {
         Label l = (Label) n.f1.f0.choice;
         String label = l.f0.toString();
         System.out.println("\tjalr " + label);
      }
      return _ret;
   }

   /**
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public R visit(Exp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public R visit(SpilledArg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(SimpleExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    */
   public R visit(Reg n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public R visit(SpillInfo n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <SPILLED>
    *       | <NOTSPILLED>
    */
   public R visit(SpillStatus n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

}
