//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   int temp= 1000;
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      //n.f3.accept(this, argu);
      Ret r= new Ret();
      //System.out.println(r1.code);
      r.code= "MAIN\n" + r1.code + "\nEND\n";
      if( n.f3.present() ) {
         for ( Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
            Ret ri= (Ret)e.nextElement().accept(this,argu);
            r.code+= ri.code + "\n";
         }
      }
      n.f4.accept(this, argu);
      System.out.println(r.code);
      return (R)r;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public R visit(StmtList n, A argu) {
      Ret r = new Ret();
   
      if(n.f0.present()){
         for (Enumeration<Node> e = n.f0.elements(); e.hasMoreElements(); ) {
            Node node = e.nextElement();
            NodeSequence seq = (NodeSequence) node;
            NodeOptional maybeLabel = (NodeOptional) seq.elementAt(0);
            Ret rStmt;
            Ret rLabel = new Ret();
            if(maybeLabel.present()) {
               rLabel = (Ret) maybeLabel.node.accept(this, argu);
            }
            rStmt= (Ret)seq.elementAt(1).accept(this, argu);

            if(maybeLabel.present())
               r.code += rLabel.code + "\n" + rStmt.code;
            else
               r.code += rStmt.code;
         }
      }
    //System.out.println(r.code+"completed\n");
    return (R) r;
}



   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public R visit(Procedure n, A argu) {
      R _ret=null;
      Ret r1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Ret r3= (Ret)n.f4.accept(this, argu);
      Ret r= new Ret();
      r.code= r1.code + " [ " + r2.code + " ]\n" ;
      r.code+= "BEGIN\n" + r3.prereq + "\nRETURN " + r3.code + "\nEND\n";

      return (R)r;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public R visit(Stmt n, A argu) {
      R _ret=
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "NOOP"
    */
   public R visit(NoOpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= "NOOP\n";
      return (R)r;
   }

   /**
    * f0 -> "ERROR"
    */
   public R visit(ErrorStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= "ERROR\n";
      return (R)r;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Exp()
    * f2 -> Label()
    */
   public R visit(CJumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code= r1.prereq+"\nCJUMP " + r1.code + " " + r2.code+"\n";
      return (R)r;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public R visit(JumpStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      r1.code= "JUMP " + r1.code+"\n";
      return (R)r1;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Exp()
    * f2 -> IntegerLiteral()
    * f3 -> Exp()
    */
   public R visit(HStoreStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r3= (Ret)n.f3.accept(this, argu);
      Ret r= new Ret();
      r.code+= "MOVE TEMP "+temp+ " "+r1.code;
      r.code+= "\nMOVE TEMP "+(temp+1)+ " "+r3.code+"\n";
      r.code+= r1.prereq + "\n" + r3.prereq+"\nHSTORE TEMP " + (temp) + " " + r2.code + " TEMP " + (temp+1)+"\n";
      temp+= 2;
      return (R)r;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Exp()
    * f3 -> IntegerLiteral()
    */
   public R visit(HLoadStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r3= (Ret)n.f3.accept(this, argu);
      Ret r= new Ret();
      r.code= r2.prereq + "\nHLOAD " + r1.code + " " + r2.code + " " + r3.code+"\n";
      return (R)r;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public R visit(MoveStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code= r2.prereq + "\nMOVE " + r1.code + " " + r2.code+"\n";
      return (R)r;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> Exp()
    */
   public R visit(PrintStmt n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r= new Ret();
      r.code= r1.prereq + "\nPRINT " + r1.code+"\n";
      return (R)r;
   }

   /**
    * f0 -> StmtExp()
    *       | Call()
    *       | HAllocate()
    *       | BinOp()
    *       | Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public R visit(Exp n, A argu) {
      R _ret=n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> Exp()
    * f4 -> "END"
    */
   public R visit(StmtExp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Ret r2= (Ret)n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      Ret r= new Ret();
      r.prereq= r1.code+ "\n" + r2.prereq;
      r.code= r2.code ;
      //System.out.println(r.prereq+"complete\n");

      return (R)r;
   }

   /**
    * f0 -> "CALL"
    * f1 -> Exp()
    * f2 -> "("
    * f3 -> ( Exp() )*
    * f4 -> ")"
    */
   public R visit(Call n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Ret r= new Ret();
      r.prereq= r1.prereq;
      String s= "MOVE TEMP "+temp+" CALL " + r1.code+ " ( ";
      if ( n.f3.present() ) {
         int _count=0;
         for ( Enumeration<Node> e = n.f3.elements(); e.hasMoreElements(); ) {
            Ret ri= (Ret)e.nextElement().accept(this,argu);
            r.prereq+= "\n" + ri.prereq;
            r.prereq+= "MOVE TEMP "+ temp+ " "+ri.code+"\n";
            s+= " TEMP " +(temp++) ;
            _count++;
         }
      }
      s+= " )\n";
      r.prereq+= s;
      r.code= "TEMP "+(temp++);
      //n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return (R)r;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> Exp()
    */
   public R visit(HAllocate n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r= new Ret();
      r.prereq= r1.prereq;
      r.prereq+="\nMOVE TEMP "+(temp)+" HALLOCATE " + r1.code;
      r.code= "TEMP "+(temp++);
      return (R)r;
   }

   /**
    * f0 -> Operator()
    * f1 -> Exp()
    * f2 -> Exp()
    */
   public R visit(BinOp n, A argu) {
      R _ret=null;
      Ret r1= (Ret)n.f0.accept(this, argu);
      Ret r2= (Ret)n.f1.accept(this, argu);
      Ret r3= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.prereq= r2.prereq + "\n" + r3.prereq;
      r.prereq+= "MOVE TEMP "+temp+" "+r2.code+"\n";
      r.prereq+= "MOVE TEMP "+(temp+1)+" "+r3.code+"\n";
      r.prereq+="MOVE TEMP "+(temp+2)+" "+ r1.code + " TEMP " +temp+ " TEMP "+(temp+1)+"\n";
      r.code+= "TEMP "+(temp+2);
      temp+= 3; 
      //System.out.println(r1.code);
      return (R)r;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public R visit(Operator n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= n.f0.choice.toString();
      //System.out.println(r.code);
      return (R)r;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public R visit(Temp n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1=(Ret)n.f1.accept(this, argu);
      Ret r= new Ret();
      r.code= "TEMP " + r1.code;
      return (R)r;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code = n.f0.tokenImage;
      return (R)r;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Label n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= n.f0.toString();
      return (R)r;
   }

}
