//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   public HashMap <String, Table> vtable = new HashMap<>();
   public HashMap <String, Classinfo> classMap = new HashMap<>();
   String curclass = "";
   String curmethod= "";
   int temp= 0;
   int label= 0;
   int lambda_count= 0;
   String lam_code="";
   String temp_cls="";
   String temp_method= "";

   String fun_search(Classinfo c, String id,String curclass){
      //System.out.println(curclass+" "+id);
      if(c.varMap.containsKey(curclass+"_"+id)){
         return c.varMap.get(curclass+"_"+id);
      }
      else if(!"@".equals(c.parent)){
         return fun_search(classMap.get(c.parent),id,c.parent);
      }
      else{
         return "";
      }
   }
   
   int fun_search_offset(Classinfo c, String id,String curclass){
      if(c.varMap.containsKey(curclass+"_"+id)){
         return vtable.get(c.className).fields.get(curclass+"_"+id);
      }
      else if(!"@".equals(c.parent)){
         return fun_search_offset(classMap.get(c.parent),id,c.parent);
      }
      else{
         return -1;
      }
   }
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void printClasses() {
    for (String cname : classMap.keySet()) {
        Classinfo ci = classMap.get(cname);
        System.out.println("Class: " + ci.className + 
                           (ci.parent.equals("@") ? "" : " extends " + ci.parent));

        // Class variables
        if (!ci.varMap.isEmpty()) {
            System.out.println("  Fields:");
            for (String vname : ci.varMap.keySet()) {
                System.out.println("    " + ci.varMap.get(vname) + " " + vname);
            }
        }

        // Class methods
        if (!ci.methodMap.isEmpty()) {
            System.out.println("  Methods:");
            for (Methodinfo mi : ci.methodMap.values()) {
                System.out.print("    " + mi.rettype + " " + mi.name + "(");

                // Arguments
                boolean first = true;
                for (String aname : mi.arguementsMap.keySet()) {
                    if (!first) System.out.print(", ");
                    System.out.print(mi.arguementsMap.get(aname) + " " + aname);
                    first = false;
                }
                System.out.println(")");

                // Local vars
                if (!mi.varMap.isEmpty()) {
                    System.out.println("      Locals:");
                    for (String vname : mi.varMap.keySet()) {
                        System.out.println("        " + mi.varMap.get(vname) + " " + vname);
                    }
                }
            }
        }
        System.out.println();
      }
   }
   
   public void printvtable(){
      for(Table t:vtable.values()){
         t.printTable();
      }
   }

   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public R visit(Goal n, A argu) {
      R _ret=null;
      //printClasses();
      n.f0.accept(this, argu);
      Ret r= (Ret)n.f1.accept(this, argu);
      System.out.println(r.code);
      //System.out.println(label);
      
      for(int i=0;i<n.f2.size();i++){
         System.out.println(((Ret)n.f2.elementAt(i).accept(this,argu)).code);
      }

      System.out.println(lam_code);
      label= 0;
      //printvtable();
      
      return (R)r;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public R visit(ImportFunction n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public R visit(MainClass n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      n.f8.accept(this, argu);
      n.f9.accept(this, argu);
      n.f10.accept(this, argu);
      n.f12.accept(this, argu);
      n.f13.accept(this, argu);
      Ret r= (Ret)n.f14.accept(this, argu);
      n.f15.accept(this, argu);
      n.f16.accept(this, argu);
      r.code = "MAIN\n"+ r.code+"END\n";
      temp= 0;
      return (R)r;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public R visit(TypeDeclaration n, A argu) {
      R _ret= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public R visit(ClassDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      curclass= n.f1.f0.toString();
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Ret r= new Ret();
      for(int i=0;i<n.f4.size();i++){
         r.code+= ((Ret)n.f4.elementAt(i).accept(this,argu)).code;
      }
      n.f5.accept(this, argu);
      curclass= "";
      return (R)r;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public R visit(ClassExtendsDeclaration n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      curclass= n.f1.f0.toString();
      n.f2.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      Ret r= new Ret();
      for(int i=0;i<n.f6.size();i++){
         r.code+= ((Ret)n.f6.elementAt(i).accept(this,argu)).code;
      }
      n.f7.accept(this, argu);
      curclass= "";
      return (R)r;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public R visit(VarDeclaration n, A argu) {
      R _ret=null;
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public R visit(MethodDeclaration n, A argu) {
      R _ret=null;
      
      n.f0.accept(this, argu);
      curmethod = n.f2.f0.toString();
      temp= classMap.get(curclass).methodMap.get(curmethod).arguements.size()+ classMap.get(curclass).methodMap.get(curmethod).vars.size()+1;
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      n.f6.accept(this, argu);
      n.f7.accept(this, argu);
      Ret r= new Ret();
      r.code= curclass+"_"+curmethod+" ["+String.valueOf(classMap.get(curclass).methodMap.get(curmethod).arguements.size()+1)+"]\nBEGIN\n";
      for(int i=0;i<n.f8.size();i++){
         r.code+= ((Ret)n.f8.elementAt(i).accept(this,argu)).code;
      }

      n.f9.accept(this, argu);
      r.code+= "RETURN ";
      r.code+= ((Ret)n.f10.accept(this,argu)).code;
      r.code+= "\nEND\n";
      curmethod="";
      temp= 0;
      return (R)r;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public R visit(FormalParameterList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public R visit(FormalParameter n, A argu) {
      R _ret=null;
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public R visit(FormalParameterRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public R visit(Type n, A argu) {
      R _ret=
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public R visit(ArrayType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public R visit(BooleanType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public R visit(IntegerType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public R visit(LambdaType n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      Ret r= new Ret();
      return (R)r;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public R visit(Statement n, A argu) {
      R _ret=
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public R visit(Block n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      for(int i= 0;i<n.f1.size();i++){
         r.code+= ((Ret)n.f1.elementAt(i).accept(this,argu)).code;
      }
      n.f2.accept(this, argu);
      return (R)r;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public R visit(AssignmentStatement n, A argu) {
      R _ret=null;
      
      n.f1.accept(this, argu);
      String id= n.f0.f0.toString();
      Ret r2= (Ret)n.f2.accept(this, (A)n.f0.f0.toString());
      n.f3.accept(this, argu);
      Ret r= new Ret();
      
      if(classMap.get(curclass).methodMap.get(curmethod).varMap.containsKey(id)){
         r.code= "MOVE "+classMap.get(curclass).methodMap.get(curmethod).varMap.get(id)+" ";
      }
      else if(classMap.get(curclass).methodMap.get(curmethod).arguementsMap.containsKey(id)){
         r.code= "MOVE "+classMap.get(curclass).methodMap.get(curmethod).arguementsMap.get(id)+" ";
      }
      else{

         r.code+= "HSTORE TEMP 0 "+4*fun_search_offset(classMap.get(curclass), id, curclass)+" ";
      }
      r.code+= r2.code;
      r.code+="\n";
      return (R)r;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public R visit(ArrayAssignmentStatement n, A argu) {
      R _ret=null;
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Ret r3= (Ret)n.f5.accept(this, argu);
      Ret r= new Ret();
      String id= n.f0.f0.toString();
      String id_temp="";
      if(classMap.get(curclass).methodMap.get(curmethod).varMap.containsKey(id)){
         id_temp= classMap.get(curclass).methodMap.get(curmethod).varMap.get(id);
      }
      else if(classMap.get(curclass).methodMap.get(curmethod).arguementsMap.containsKey(id)){
         id_temp= classMap.get(curclass).methodMap.get(curmethod).arguementsMap.get(id);
      }
      else{
         id_temp= "TEMP "+temp++;

         r.code+= "HLOAD "+id_temp+" TEMP 0 "+(4*fun_search_offset(classMap.get(curclass), id, curclass))+"\n";
      }
      r.code+= "HSTORE PLUS "+id_temp+" PLUS 4 TIMES 4 "+r2.code+" 0 ";
      r.code+= r3.code+"\n";
      return (R)r;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public R visit(IfStatement n, A argu) {
      R _ret=n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(IfthenStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      String label1= "L"+(label++);
      n.f1.accept(this, argu);
      Ret r1= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Ret r2= (Ret)n.f4.accept(this, argu);
      Ret r= new Ret();
      r.code= "CJUMP "+r1.code+ " "+label1+"\n";
      r.code+= r2.code;
      r.code+= label1+"\nNOOP\n";
      return (R)r;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public R visit(IfthenElseStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      Ret r1= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Ret r2= (Ret)n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      Ret r3= (Ret)n.f6.accept(this, argu);
      Ret r= new Ret();
      r.code= "CJUMP "+r1.code+ " "+label1+"\n";
      r.code+= r2.code;
      r.code+= "JUMP "+label2+"\n";
      r.code+= label1+"\n";
      r.code+= r3.code;
      r.code+= label2+"\nNOOP\n";
      return (R)r;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public R visit(WhileStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r1= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      Ret r2= (Ret)n.f4.accept(this, argu);
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      Ret r= new Ret();
      r.code= label1+"\n";
      r.code+= "CJUMP "+r1.code+ " "+ label2+"\n";
      r.code+= r2.code;
      r.code+= "JUMP "+label1+"\n";
      r.code+= label2+"\nNOOP\n";
      return (R)r;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public R visit(PrintStatement n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      Ret r1= new Ret();
      r1.code= "PRINT "+ r.code+"\n";
      return (R)r1;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public R visit(Expression n, A argu) {
      R _ret=
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public R visit(LambdaExpression n, A argu) {

      R _ret=null;
      String id= (String)argu;
      String id2= n.f1.f0.toString();
      
      if(classMap.get(curclass).methodMap.get(curmethod).varMap.containsKey(id)){
         
         String s= classMap.get(curclass).methodMap.get(curmethod).typeVar.get(id);
         if(s.startsWith("Function<") ){
            
            String[] parts= s.substring(9,s.length()-1).split(",");
            String arg1= parts[0].trim();
            String arg2= parts[1].trim();
            lambda_count++;
            String lam_name= "lambda_"+lambda_count;
            Classinfo c= new Classinfo(lam_name,"@");
            Methodinfo m= new Methodinfo("apply",arg2);
            m.arguements.add(id2);
            m.arguementsMap.put(id2,"TEMP 1");
            m.typeArg.put(id2, arg1);
            c.pushmethod(m);
            classMap.put(id,c);

            Table t= new Table();
            t.methods.put("apply", 0);
            t.argsize.put("apply", 1);
            t.source.put("apply", lam_name);
            t.name= lam_name;
            vtable.put(lam_name,t);

         }
      }
      else if(classMap.get(curclass).methodMap.get(curmethod).arguementsMap.containsKey(id)){
         String s= classMap.get(curclass).methodMap.get(curmethod).typeArg.get(id);
         if(s.startsWith("Function<") ){
            String[] parts= s.substring(9,s.length()-1).split(",");
            String arg1= parts[0].trim();
            String arg2= parts[1].trim();
            lambda_count++;
            String lam_name= "lambda_"+lambda_count;
            Classinfo c= new Classinfo(lam_name,"@");
            Methodinfo m= new Methodinfo("apply",arg2);
            m.arguements.add(id2);
            m.arguementsMap.put(id2,"TEMP 1");
            m.typeArg.put(id2, arg1);
            c.pushmethod(m);
            classMap.put(id,c);

            Table t= new Table();
            t.methods.put("apply", 0);
            t.argsize.put("apply", 1);
            t.source.put("apply", lam_name);
            t.name= lam_name;
            vtable.put(lam_name,t);

         }
      }
      else{
         String s= fun_search(classMap.get(curclass), id, curclass);
         if(s.startsWith("Function<") ){
            String[] parts= s.substring(9,s.length()-1).split(",");
            String arg1= parts[0].trim();
            String arg2= parts[1].trim();
            lambda_count++;
            String lam_name= "lambda_"+lambda_count;
            Classinfo c= new Classinfo(lam_name,"@");
            Methodinfo m= new Methodinfo("apply",arg2);
            m.arguements.add(id2);
            m.arguementsMap.put(id2,"TEMP 1");
            m.typeArg.put(id2, arg1);
            c.pushmethod(m);
            classMap.put(id,c);

            Table t= new Table();
            t.methods.put("apply", 0);
            t.argsize.put("apply", 1);
            t.source.put("apply", lam_name);
            t.name= lam_name;
            vtable.put(lam_name,t);
         }
      }
      String t1= "TEMP "+temp++;
      String t2= "TEMP "+temp++;
      
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      
      Ret r= new Ret();
      r.code= "BEGIN\n";
      String lam_name= "lambda_"+(lambda_count);
      int variables= classMap.get(curclass).methodMap.get(curmethod).arguements.size()+ 
      classMap.get(curclass).methodMap.get(curmethod).vars.size()+
      classMap.get(curclass).varMap.size()+1;
      r.code+= "MOVE "+t2+" HALLOCATE "+(4*variables)+"\n";
      r.code+= "MOVE "+t1+" HALLOCATE 4\n";
      r.code+= "HSTORE "+t1+" 0 "+lam_name+"_apply\n";
      r.code+= "HSTORE "+t2+" 0 "+t1+"\n";
      HashSet <String> temp_set= new HashSet<>();
      Methodinfo m= classMap.get(curclass).methodMap.get(curmethod);
      for(int i=0;i< m.arguements.size();i++){
         r.code+= "HSTORE "+t2+" "+(4*i+4)+" "+
         m.arguementsMap.get(m.arguements.get(i))+"\n";
         temp_set.add(m.arguements.get(i));
      }
      //printClasses();
      for(int i=0;i< m.vars.size();i++){
         r.code+= "HSTORE "+t2+" "+(4*(i+1+classMap.get(curclass).methodMap.get(curmethod).arguements.size()))+" "+
         m.varMap.get(m.vars.get(i))+"\n";
         temp_set.add(m.vars.get(i));
      }
      
      int i=1;
      for(String s:classMap.get(curclass).varMap.keySet()){
         String fieldName = s.substring(s.indexOf("_")+1);
         if(!temp_set.contains(fieldName)){
            r.code+= "HLOAD "+"TEMP "+temp+ " TEMP 0 "+ vtable.get(curclass).fields.get(s)+"\n";
            r.code+= "HSTORE "+t2+" "+(4*(i+m.arguements.size()+m.vars.size()))+ " TEMP "+ (temp++)+"\n";

            i++;
         }
      }
      
      r.code+= "RETURN "+t2+"\nEND\n";
      temp_cls= curclass;
      curclass= id;
      temp_method= curmethod;
      curmethod= "apply";
      //printClasses();
      Ret r1= (Ret)n.f4.accept(this, argu);
      
      curclass= temp_cls;
      curmethod= temp_method;
      lam_code+= lam_name+"_apply [1]\nBEGIN\n";
      lam_code+= "RETURN "+ r1.code+"\nEND\n";
      //System.out.println(lam_code);
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public R visit(AndExpression n, A argu) {
      R _ret=null;
      Ret B1 = (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret B2 = (Ret)n.f2.accept(this, argu);
      Ret B= new Ret();
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      String t= "TEMP "+temp++; 
      B.code= "BEGIN\nCJUMP "+ B1.code+ " "+label1+"\nCJUMP "+ B2.code+ " "+label1+"\n";
      B.code+= "MOVE "+t+ " 1\nJUMP "+label2+"\n";
      B.code+= label1+"\n"+"MOVE "+t+ " 0\n"+label2+"\nNOOP\n";
      B.code+= "RETURN "+t+"\n"+"END\n";

      return (R)B;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public R visit(OrExpression n, A argu) {
      R _ret=null;
      Ret B1 = (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret B2 = (Ret)n.f2.accept(this, argu);
      Ret B= new Ret();
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      String label3= "L"+(label++);
      String t= "TEMP "+temp++; 
      B.code= "BEGIN\nCJUMP "+ B1.code+ " "+label1+"\n";
      B.code+= "MOVE "+t+" 1\nJUMP "+label2+"\n";
      B.code+= label1+"\n"+
      "CJUMP "+ B2.code+  " "+label3+"\n";
      
      B.code+= "MOVE "+t+ " 1\nJUMP "+label2+"\n"+label3+"\n";
      B.code+= "MOVE "+t+" 0\n"+label2+"\nNOOP\n";
      B.code+= "RETURN "+t+"\n"+"END\n";

      return (R)B;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public R visit(CompareExpression n, A argu) {
      R _ret=null;
      Ret E1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret E2= (Ret)n.f2.accept(this, argu);
      Ret B= new Ret();
      B.code= E1.code+ E2.code;
      B.code=  "LE "+ E1.code+ " " +E2.code;  
      return (R)B;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public R visit(neqExpression n, A argu) {
      R _ret=null;
      Ret E1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret E2= (Ret)n.f2.accept(this, argu);
      Ret B= new Ret();
      B.code= E1.code+ E2.code;
      B.code=  "NE "+ E1.code+ " "+E2.code;  
      return (R)B;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public R visit(AddExpression n, A argu) {
      R _ret=null;
      
      Ret r1= (Ret)n.f0.accept(this, argu);
      
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code=r1.code+r2.code;
      r.code= "PLUS "+r1.code+ " "+ r2.code; 
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public R visit(MinusExpression n, A argu) {
      Ret r1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code=r1.code+r2.code;
      r.code= "MINUS "+r1.code+ " "+ r2.code; 
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public R visit(TimesExpression n, A argu) {
      Ret r1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code=r1.code+r2.code;
      r.code= "TIMES "+r1.code+ " "+ r2.code; 
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public R visit(DivExpression n, A argu) {
      Ret r1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code=r1.code+r2.code;
      r.code= "DIV "+r1.code+ " "+ r2.code; 
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public R visit(ArrayLookup n, A argu) {
      R _ret=null;
      String t= "TEMP "+temp++;
      Ret r= new Ret();
      Ret r1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      Ret r2= (Ret)n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      r.code+= "BEGIN\nHLOAD "+t+" PLUS "+r1.code+ "PLUS 4 TIMES 4 "+ r2.code+ " 0\n";
      r.code+= "RETURN "+t+"\nEND\n";
      r.Type= "int";
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public R visit(ArrayLength n, A argu) {
      R _ret=null;
      String t= "TEMP "+temp++;
      Ret r1= (Ret)n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      Ret r= new Ret();
      r.code+= "BEGIN\nHLOAD "+t+" "+r1.code+ " 0\n";
      r.code+= "RETURN "+t+"\nEND\n";
      r.Type= "int";
      return (R)r;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public R visit(MessageSend n, A argu) {
      R _ret=null;
      String t1= "TEMP "+temp++;
      String t2= "TEMP "+temp++;
      String t3= "TEMP "+temp++;
      Ret r= new Ret();
      Ret r1= (Ret)n.f0.accept(this, (A)"call");
      temp_cls= r1.code;
      n.f1.accept(this, argu);
      String fun= n.f2.f0.toString();
      //System.out.println(r1.Type+" "+fun);
      n.f3.accept(this, argu);
      
      r.code= "CALL\nBEGIN\n";
      r.code+= "MOVE "+t1+" "+r1.code+"\n";
      r.code+= "HLOAD "+t2+" "+t1+" 0\n";
      if((r1.Type).startsWith("Function<")){
         r.code+= "HLOAD "+t3+" "+t2+" "+0+"\n";
         r.Type= r1.next;
      }
      else {
         r.code+= "HLOAD "+t3+" "+t2+" "+(4*(vtable.get(r1.Type).methods.get(fun)))+"\n";
         r.Type= classMap.get(r1.Type).methodMap.get(fun).rettype;
      }
      r.code+= "RETURN "+t3+"\nEND\n";
      n.f4.accept(this, argu);
      n.f5.accept(this, argu);
      ExpressionList e= (ExpressionList)n.f4.node;
      r.code+= "( "+t1+ " ";
      if(e!= null){
         for(int i=0;i<= e.f1.nodes.size();i++){
            if(i==0){
               r.code+= ((Ret)e.f0.accept(this, argu)).code+" ";
            }
            else{
               ExpressionRest er= (ExpressionRest)e.f1.nodes.get(i-1);
               r.code+= ((Ret)er.f1.accept(this, argu)).code+" ";
            }
         }
      }
      r.code+= " )\n";
      
      return (R)r;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public R visit(ExpressionList n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public R visit(ExpressionRest n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public R visit(PrimaryExpression n, A argu) {
      R _ret=
      n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(IntegerLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= n.f0.toString();
      return (R)r;
   }

   /**
    * f0 -> "true"
    */
   public R visit(TrueLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= "1";
      return (R)r;
   }

   /**
    * f0 -> "false"
    */
   public R visit(FalseLiteral n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= "0";
      return (R)r;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      
      Ret r= new Ret();
      String id= n.f0.toString();
      //System.out.println(curclass);
      
      if(classMap.get(curclass).methodMap.get(curmethod).varMap.containsKey(id)){
         r.code= classMap.get(curclass).methodMap.get(curmethod).varMap.get(id);
      }
      else if(classMap.get(curclass).methodMap.get(curmethod).arguementsMap.containsKey(id)){
         
         r.code= classMap.get(curclass).methodMap.get(curmethod).arguementsMap.get(id);
      }
      else{
         String t= "TEMP "+temp++;
         r.code+= "BEGIN\nHLOAD "+t+ " TEMP 0 "+String.valueOf(4*fun_search_offset(classMap.get(curclass), id, curclass))+"\n";
         r.code+= "RETURN "+t+"\nEND\n";
         
      }
      
      if(((String)argu).equals("call")){
         
         if(classMap.get(curclass).methodMap.get(curmethod).varMap.containsKey(id)){
         r.Type= classMap.get(curclass).methodMap.get(curmethod).typeVar.get(id);
         if(r.Type.startsWith("Function<")){
            String[] parts= r.Type.substring(9,r.Type.length()-1).split(",");
            r.next= parts[1].trim();
         }
         }
         else if(classMap.get(curclass).methodMap.get(curmethod).arguementsMap.containsKey(id)){
         r.Type= classMap.get(curclass).methodMap.get(curmethod).typeArg.get(id);
         if(r.Type.startsWith("Function<")){
            String[] parts= r.Type.substring(9,r.Type.length()-1).split(",");
            r.next= parts[1].trim();
         }
         }
         else{
            r.Type= fun_search(classMap.get(curclass), id, curclass);
            if(r.Type.startsWith("Function<")){
            String[] parts= r.Type.substring(9,r.Type.length()-1).split(",");
            r.next= parts[1].trim();
            }
         }
         //System.out.println(r.Type+" "+id);
         
      }

      
      return (R)r;
   }

   /**
    * f0 -> "this"
    */
   public R visit(ThisExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r= new Ret();
      r.code= "TEMP 0";
      r.Type= curclass;
      return (R)r;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public R visit(ArrayAllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      
      Ret r1= (Ret)n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      String t1= "TEMP "+temp++;
      String t2= "TEMP "+temp++;
      Ret r= new Ret();
      r.code = "BEGIN\n";
      r.code+= "MOVE "+ t1+" HALLOCATE PLUS 4 TIMES 4 "+r1.code+"\n";
      r.code+= "HSTORE "+t1+ " 0 "+ r1.code+"\n";
      r.code+= "MOVE "+t2+ " 4\n";
      r.code+= label1+"\n";
      r.code+= "CJUMP LE "+t2+ " TIMES 4 "+r1.code+" "+label2+"\n";
      r.code+= "HSTORE PLUS "+t1+ " "+ t2+ " 0 0\n";
      r.code+= "MOVE "+t2+ " PLUS "+t2+ " 4\n";
      r.code+= "JUMP "+label1+"\n";
      r.code+= label2+"\nNOOP\n";
      r.code+= "RETURN "+t1+"\nEND\n";
      r.Type= "int[]";
      return (R)r;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public R visit(AllocationExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      String cls= n.f1.f0.toString();
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      String t1= "TEMP "+temp++;
      String t2= "TEMP "+temp++;
      String t3= "TEMP "+temp++;
      Ret r= new Ret();
      r.code = "BEGIN\n";
      int method_count= classMap.get(cls).methodMap.size();
      int field_count= classMap.get(cls).varMap.size();
      r.code+= "MOVE "+ t1+" HALLOCATE "+(4*method_count)+"\n";
      r.code+= "MOVE "+ t2+" HALLOCATE "+(4*field_count+4)+"\n";
      for (String s: vtable.get(cls).methods.keySet()){
         String ogcls= vtable.get(cls).source.get(s);
         int offset= vtable.get(cls).methods.get(s);
         r.code+= "HSTORE "+t1+" "+4*offset+" "+ogcls+"_"+s+"\n";
      }
      r.code+= "HSTORE "+t2+ " 0 "+ t1+"\n";
      r.code+= "MOVE "+t3+ " 4\n";
      r.code+= label1+"\n";
      r.code+= "CJUMP LE "+t3+ " TIMES 4 "+field_count+" "+label2+"\n";
      r.code+= "HSTORE PLUS "+t2+ " "+ t3+ " 0 0\n";
      r.code+= "MOVE "+t3+ " PLUS "+t3+ " 4\n";
      r.code+= "JUMP "+label1+"\n";
      r.code+= label2+"\nNOOP\n";
      r.code+= "RETURN "+t2+"\nEND\n";
      r.Type= cls;
      return (R)r;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public R visit(NotExpression n, A argu) {
      R _ret=null;
      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      Ret r= new Ret();
      String label1= "L"+(label++);
      String label2= "L"+(label++);
      String t= "TEMP "+temp++;
      r.code= "BEGIN\n";
      r.code+= "CJUMP "+ r1.code+ " "+ label1+"\n";
      r.code+= "MOVE "+t+ " 0\nJUMP "+label2+"\n";
      r.code+= label1+"\n";
      r.code+= "MOVE "+t+ " 1\n";
      r.code+= label2+"\nNOOP\n"+"RETURN "+t+"\nEND";
      r.Type= "boolean";
      _ret= (R)r;
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public R visit(BracketExpression n, A argu) {
      R _ret=null;

      n.f0.accept(this, argu);
      Ret r1= (Ret)n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      return (R)r1;
   }

}
