//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class LambdaEliminate implements GJVisitor<String,String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public class lambda{
      String name;
      String arg;
      String body;
      public lambda(String n, String a, String b){
         name=n;
         arg=a;
         body=b;
      }
   }
   HashMap<String,lambda> lambdas = new HashMap<String,lambda>();
   int lambda_count=0;
   public String visit(NodeList n, String argu) {
      String _ret= "";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret+= e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeListOptional n, String argu) {
      if ( n.present() ) {
         String _ret= "";
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            _ret+= e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return "";
   }

   public String visit(NodeOptional n, String argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return "";
   }

   public String visit(NodeSequence n, String argu) {
      String _ret= "";
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         _ret+= e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public String visit(NodeToken n, String argu) { return ""; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( ImportFunction() )?
    * f1 -> MainClass()
    * f2 -> ( TypeDeclaration() )*
    * f3 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String _ret= "";
      _ret+= n.f1.accept(this, argu);
      _ret+= n.f2.accept(this, argu);
      _ret+= n.f3.accept(this, argu);
      System.out.println(_ret);
      return _ret;
   }

   /**
    * f0 -> "import"
    * f1 -> "java.util.function.Function"
    * f2 -> ";"
    */
   public String visit(ImportFunction n, String argu) {
      String _ret= "";
      _ret+= "import ";
      _ret+= "java.util.function.Function";
      _ret+= ";\n";
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> "public"
    * f4 -> "static"
    * f5 -> "void"
    * f6 -> "main"
    * f7 -> "("
    * f8 -> "String"
    * f9 -> "["
    * f10 -> "]"
    * f11 -> Identifier()
    * f12 -> ")"
    * f13 -> "{"
    * f14 -> PrintStatement()
    * f15 -> "}"
    * f16 -> "}"
    */
   public String visit(MainClass n, String argu) {
      String _ret= "";
      _ret+= "class ";
      _ret+= n.f1.accept(this, argu);
      _ret+= " {\n";
      _ret+= "public ";
      _ret+= "static ";
      _ret+= "void ";
      _ret+= "main";
      _ret+= "(";
      _ret+= "String";
      _ret+= "[";
      _ret+= "] ";
      _ret+= n.f11.accept(this, argu);
      _ret+= ") {\n";
      _ret+= n.f14.accept(this, argu);
      _ret+= "}\n";
      _ret+= "}\n";
      return _ret;
   }

   /**
    * f0 -> ClassDeclaration()
    *       | ClassExtendsDeclaration()
    */
   public String visit(TypeDeclaration n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "{"
    * f3 -> ( VarDeclaration() )*
    * f4 -> ( MethodDeclaration() )*
    * f5 -> "}"
    */
   public String visit(ClassDeclaration n, String argu) {
      String _ret= "";
      _ret+= "class ";
      _ret+= n.f1.accept(this, argu);
      _ret+= " {\n";
      _ret+= n.f3.accept(this, argu);
      _ret+= n.f4.accept(this, argu);
      _ret+= "}\n";
      return _ret;
   }

   /**
    * f0 -> "class"
    * f1 -> Identifier()
    * f2 -> "extends"
    * f3 -> Identifier()
    * f4 -> "{"
    * f5 -> ( VarDeclaration() )*
    * f6 -> ( MethodDeclaration() )*
    * f7 -> "}"
    */
   public String visit(ClassExtendsDeclaration n, String argu) {
      String _ret= "";
      _ret+= "class ";
      _ret+= n.f1.accept(this, argu);
      _ret+= " extends ";
      _ret+= n.f3.accept(this, argu);
      _ret+= " {\n";
      _ret+= n.f5.accept(this, argu);
      _ret+= n.f6.accept(this, argu);
      _ret+= "}\n";
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    * f2 -> ";"
    */
   public String visit(VarDeclaration n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " ";
      _ret+= n.f1.accept(this, argu);
      _ret+= ";\n";
      return _ret;
   }

   /**
    * f0 -> "public"
    * f1 -> Type()
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( FormalParameterList() )?
    * f5 -> ")"
    * f6 -> "{"
    * f7 -> ( VarDeclaration() )*
    * f8 -> ( Statement() )*
    * f9 -> "return"
    * f10 -> Expression()
    * f11 -> ";"
    * f12 -> "}"
    */
   public String visit(MethodDeclaration n, String argu) {
      String _ret= "";
      _ret+= "public ";
      _ret+= n.f1.accept(this, argu);
      _ret+= " ";
      _ret+= n.f2.accept(this, argu);
      _ret+= "(";
      _ret+= (n.f4.present() ? n.f4.accept(this, argu) : "");
      _ret+= ") {\n";
      _ret+= n.f7.accept(this, argu);
      _ret+= n.f8.accept(this, argu);
      _ret+= "return ";
      _ret+= n.f10.accept(this, argu);
      _ret+= ";\n}\n";
      return _ret;
   }

   /**
    * f0 -> FormalParameter()
    * f1 -> ( FormalParameterRest() )*
    */
   public String visit(FormalParameterList n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> Type()
    * f1 -> Identifier()
    */
   public String visit(FormalParameter n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " ";
      _ret+= n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> FormalParameter()
    */
   public String visit(FormalParameterRest n, String argu) {
      String _ret= "";
      _ret+= ", ";
      _ret+= n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ArrayType()
    *       | BooleanType()
    *       | IntegerType()
    *       | Identifier()
    *       | LambdaType()
    */
   public String visit(Type n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "int"
    * f1 -> "["
    * f2 -> "]"
    */
   public String visit(ArrayType n, String argu) {
      String _ret= "";
      _ret+= "int";
      _ret+= "[";
      _ret+= "]";
      return _ret;
   }

   /**
    * f0 -> "boolean"
    */
   public String visit(BooleanType n, String argu) {
      String _ret= "";
      _ret+= "boolean";
      return _ret;
   }

   /**
    * f0 -> "int"
    */
   public String visit(IntegerType n, String argu) {
      String _ret= "";
      _ret+= "int";
      return _ret;
   }

   /**
    * f0 -> "Function"
    * f1 -> "<"
    * f2 -> Identifier()
    * f3 -> ","
    * f4 -> Identifier()
    * f5 -> ">"
    */
   public String visit(LambdaType n, String argu) {
      String _ret= "";
      _ret+= "Func";
      _ret+= "_";
      _ret+= n.f2.accept(this, argu);
      _ret+= ", ";
      _ret+= n.f4.accept(this, argu);

      
      return _ret;
   }

   /**
    * f0 -> Block()
    *       | AssignmentStatement()
    *       | ArrayAssignmentStatement()
    *       | IfStatement()
    *       | WhileStatement()
    *       | PrintStatement()
    */
   public String visit(Statement n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "{"
    * f1 -> ( Statement() )*
    * f2 -> "}"
    */
   public String visit(Block n, String argu) {
      String _ret= "";
      _ret+= "{\n";
      _ret+= n.f1.accept(this, argu);
      _ret+= "}\n";
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "="
    * f2 -> Expression()
    * f3 -> ";"
    */
   public String visit(AssignmentStatement n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " = ";
      _ret+= n.f2.accept(this, argu);
      _ret+= ";\n";
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> "["
    * f2 -> Expression()
    * f3 -> "]"
    * f4 -> "="
    * f5 -> Expression()
    * f6 -> ";"
    */
   public String visit(ArrayAssignmentStatement n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= "[";
      _ret+= n.f2.accept(this, argu);
      _ret+= "] = ";
      _ret+= n.f5.accept(this, argu);
      _ret+= ";\n";
      return _ret;
   }

   /**
    * f0 -> IfthenElseStatement()
    *       | IfthenStatement()
    */
   public String visit(IfStatement n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public String visit(IfthenStatement n, String argu) {
      String _ret= "";
      _ret+= "if ";
      _ret+= "(";
      _ret+= n.f2.accept(this, argu);
      _ret+= ") ";
      _ret+= n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "if"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    * f5 -> "else"
    * f6 -> Statement()
    */
   public String visit(IfthenElseStatement n, String argu) {
      String _ret= "";
      _ret+= "if ";
      _ret+= "(";
      _ret+= n.f2.accept(this, argu);
      _ret+= ") ";
      _ret+= n.f4.accept(this, argu);
      _ret+= " else ";
      _ret+= n.f6.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "while"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> Statement()
    */
   public String visit(WhileStatement n, String argu) {
      String _ret= "";
      _ret+= "while ";
      _ret+= "(";
      _ret+= n.f2.accept(this, argu);
      _ret+= ") ";
      _ret+= n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "System.out.println"
    * f1 -> "("
    * f2 -> Expression()
    * f3 -> ")"
    * f4 -> ";"
    */
   public String visit(PrintStatement n, String argu) {
      String _ret= "";
      _ret+= "System.out.println";
      _ret+= "(";
      _ret+= n.f2.accept(this, argu);
      _ret+= ");\n";
      return _ret;
   }

   /**
    * f0 -> OrExpression()
    *       | AndExpression()
    *       | CompareExpression()
    *       | neqExpression()
    *       | AddExpression()
    *       | MinusExpression()
    *       | TimesExpression()
    *       | DivExpression()
    *       | ArrayLookup()
    *       | ArrayLength()
    *       | MessageSend()
    *       | LambdaExpression()
    *       | PrimaryExpression()
    */
   public String visit(Expression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Identifier()
    * f2 -> ")"
    * f3 -> "->"
    * f4 -> Expression()
    */
   public String visit(LambdaExpression n, String argu) {
      String _ret= "";
      _ret+= "(";
      _ret+= n.f1.accept(this, argu);
      _ret+= ") -> ";
      _ret+= n.f4.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "&&"
    * f2 -> PrimaryExpression()
    */
   public String visit(AndExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " && ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "||"
    * f2 -> PrimaryExpression()
    */
   public String visit(OrExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " || ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "<="
    * f2 -> PrimaryExpression()
    */
   public String visit(CompareExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " <= ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "!="
    * f2 -> PrimaryExpression()
    */
   public String visit(neqExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " != ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "+"
    * f2 -> PrimaryExpression()
    */
   public String visit(AddExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " + ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "-"
    * f2 -> PrimaryExpression()
    */
   public String visit(MinusExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " - ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "*"
    * f2 -> PrimaryExpression()
    */
   public String visit(TimesExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " * ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "/"
    * f2 -> PrimaryExpression()
    */
   public String visit(DivExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= " / ";
      _ret+= n.f2.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "["
    * f2 -> PrimaryExpression()
    * f3 -> "]"
    */
   public String visit(ArrayLookup n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= "[";
      _ret+= n.f2.accept(this, argu);
      _ret+= "]";
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> "length"
    */
   public String visit(ArrayLength n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= ".length";
      return _ret;
   }

   /**
    * f0 -> PrimaryExpression()
    * f1 -> "."
    * f2 -> Identifier()
    * f3 -> "("
    * f4 -> ( ExpressionList() )?
    * f5 -> ")"
    */
   public String visit(MessageSend n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= ".";
      _ret+= n.f2.accept(this, argu);
      _ret+= "(";
      _ret+= (n.f4.node != null ? n.f4.accept(this, argu) : "");
      _ret+= ")";
      return _ret;
   }

   /**
    * f0 -> Expression()
    * f1 -> ( ExpressionRest() )*
    */
   public String visit(ExpressionList n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      _ret+= n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> ","
    * f1 -> Expression()
    */
   public String visit(ExpressionRest n, String argu) {
      String _ret= "";
      _ret+= ", ";
      _ret+= n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> IntegerLiteral()
    *       | TrueLiteral()
    *       | FalseLiteral()
    *       | Identifier()
    *       | ThisExpression()
    *       | ArrayAllocationExpression()
    *       | AllocationExpression()
    *       | NotExpression()
    *       | BracketExpression()
    */
   public String visit(PrimaryExpression n, String argu) {
      String _ret= "";
      _ret+= n.f0.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      String _ret= "";
      _ret+= n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> "true"
    */
   public String visit(TrueLiteral n, String argu) {
      String _ret= "";
      _ret+= "true";
      return _ret;
   }

   /**
    * f0 -> "false"
    */
   public String visit(FalseLiteral n, String argu) {
      String _ret= "";
      _ret+= "false";
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Identifier n, String argu) {
      String _ret= "";
      _ret+= n.f0.toString();
      return _ret;
   }

   /**
    * f0 -> "this"
    */
   public String visit(ThisExpression n, String argu) {
      String _ret= "";
      _ret+= "this";
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> "int"
    * f2 -> "["
    * f3 -> Expression()
    * f4 -> "]"
    */
   public String visit(ArrayAllocationExpression n, String argu) {
      String _ret= "";
      _ret+= "new ";
      _ret+= "int";
      _ret+= "[";
      _ret+= n.f3.accept(this, argu);
      _ret+= "]";
      return _ret;
   }

   /**
    * f0 -> "new"
    * f1 -> Identifier()
    * f2 -> "("
    * f3 -> ")"
    */
   public String visit(AllocationExpression n, String argu) {
      String _ret= "";
      _ret+= "new ";
      _ret+= n.f1.accept(this, argu);
      _ret+= "()";
      return _ret;
   }

   /**
    * f0 -> "!"
    * f1 -> Expression()
    */
   public String visit(NotExpression n, String argu) {
      String _ret= "";
      _ret+= "!";
      _ret+= n.f1.accept(this, argu);
      return _ret;
   }

   /**
    * f0 -> "("
    * f1 -> Expression()
    * f2 -> ")"
    */
   public String visit(BracketExpression n, String argu) {
      String _ret= "";
      _ret+= "(";
      _ret+= n.f1.accept(this, argu);
      _ret+= ")";
      return _ret;
   }

}
